version: "3.9"

services:

  database:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network


  backend:
    build: ./backend
    container_name: backend-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: myappdb
    depends_on:
      - database
    networks:
      - app-network


  frontend:
    build: ./frontend
    container_name: frontend-ui
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
    driver: bridge
